### 📌 Inscription d'un nouvel utilisateur
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "user",
  "password": "123",
  "email": "a@bc.com"

}

### 📌 Connexion et récupération du token
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "a@bc.com",
  "password": "123"
}

### Test du endpoint sécurisé (Google JWT)
GET http://localhost:8080/auth/secured
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwcm92aWRlciI6IkdPT0dMRSIsIm5hbWUiOiJCcml4b3JyIiwiaWQiOiIxZDY5M2QzNi03Mzk2LTRmZGMtODViYi1jZjFlYmFmZGI0YjQiLCJlbWFpbCI6ImV2ZXJsaW1pdGVAbGl2ZS5mciIsInN1YiI6ImV2ZXJsaW1pdGVAbGl2ZS5mciIsImlhdCI6MTczOTk2OTkwNSwiZXhwIjoxNzQxNDA5OTA1fQ.eFB2PXXfSPKaS771x0bB5NlSSPR6nZeu0KYixSSp-yg

### Test du endpoint sécurisé (Facebook JWT)
GET http://localhost:8080/auth/secured
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwcm92aWRlciI6IkZBQ0VCT09LIiwibmFtZSI6IkZpc25payBEdXJha3UiLCJpZCI6ImNmODlmMTg4LTAyZWQtNDc3YS1iNTJkLTU3ZDJkODA5NzhlOCIsImVtYWlsIjoiYWxiYS1lbWlAaG90bWFpbC5jb20iLCJzdWIiOiJhbGJhLWVtaUBob3RtYWlsLmNvbSIsImlhdCI6MTczOTk3MzY1NSwiZXhwIjoxNzQxNDEzNjU1fQ.pNXtpsgLQUVf28KILT8eNGteCemOnYuaJOd6cYG7SI0